### ISSUE TITLE
replace_config required

### ISSUE THREAD

**Issue by t2d** [napalm-automation/napalm#129]
Ansible task:
```
- name: Push configuration with napalm
  napalm_install_config:
    hostname: "{{ inventory_hostname }}.{{ domain }}"
    dev_os: ios
    username: "{{ user }}"
    password: "{{ password }}"
    config_file: cisco-configs/{{ inventory_hostname }}/configuration
    commit_changes: False
    diff_file: cisco-config/{{ inventory_hostname }}/diff
```
Ansible output:
```
TASK: [cisco-ios | Push configuration with napalm] **************************** 
failed: [host1] => {"failed": true}
msg: missing required arguments: replace_config
failed: [host2] => {"failed": true}
msg: missing required arguments: replace_config
```
but the code says
```
replace_config:
        description: If set to True the entire configuration on the device will be replaced during the commit. If
                     set to False, we will merge the new config with the existing one. Default: False.
        required: False
```
