### ISSUE TITLE
IOS-XR NETCONF - Create clearer error indication messages when "cli" is not supported

### ISSUE THREAD

**Issue by ktbyers** [napalm-automation/napalm#1389]
This is on a connection.load_replace_candidate(filename=filename) operation

Using:

```yaml
iosxr_netconf:
  device_type: iosxr_netconf
  hostname: device.domain.com
  username: admin
  password: password
  optional_args:
    config_encoding: cli 
```

```
E           napalm.base.exceptions.ReplaceConfigException: {'type': 'protocol', 'tag': 'unknown-namespace', 'severity': 'error', 'info': '<?xml version="1.0" encoding="UTF-8"?><error-info xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0">\n   <bad-element>cli</bad-element>\n   <bad-namespace>http://cisco.com/ns/yang/Cisco-IOS-XR-cli-cfg</bad-namespace>\n  </error-info>\n ', 'path': None, 'message': None}
```

We should indicate that "cli" is not supported on this platform and the minimum IOS-XR version where "cli" is supported.
