### ISSUE TITLE
[IOS-XE] Cannot Remove Active BGP

### ISSUE THREAD

**Issue by dwi2214** [napalm-automation/napalm#1833]
### Description of Issue/Question

I would like to use load config/replace to remove the configuration BGP, but when I try to remove an Active BGP, it says failed.

I've already tried manually shutting down bgp, and using napalm to remove the peer has worked.
But is there a workaround that would increase its automation?

Thank you!

*Note*: Please check https://guides.github.com/features/mastering-markdown/
to see how to properly format your request.

### Did you follow the steps from https://github.com/napalm-automation/napalm#faq
(Place an ``x`` between the square brackets where applicable)

- [x] Yes
- [] No

### napalm version
(Paste verbatim output from `pip freeze | grep napalm` between quotes below)

```
napalm==4.0.0
napalm-ansible==1.1.0
```

### Network operating system version
(Paste verbatim output from `show version` - or equivalent - between quotes below)

```
Cisco IOS XE Software, Version 03.16.02.S - Extended Support Release
Cisco IOS Software, ASR1000 Software (X86_64_LINUX_IOSD-UNIVERSALK9-M), Version 15.5(3)S2, RELEASE SOFTWARE (fc2)
```

### Steps to Reproduce the Issue
```
---
- hosts: cisco
  gather_facts: no
  connection: local
  vars:
    - ansible_python_interpreter: /usr/local/bin/python3.8
  tasks:
    - name: "deploy"
      napalm_install_config:
          dev_os: "ios"
          config_file: "napalm-asr"
          replace_config: true
          username: 123
          password: 123
          commit_changes: true
          get_diffs: true
          diff_file: "initial.diff"
```

Running Config on Cisco :
```
router bgp 1321
 bgp log-neighbor-changes
 neighbor INIGROUP peer-group
 neighbor INIGROUP remote-as 4761
 neighbor 12.12.12.26 peer-group INIGROUP
 !
 address-family ipv4
  neighbor 12.12.12.26 activate
 exit-address-family
```

Candidate Config (napalm-asr)
(to remove neighbor 12.12.12.26 and remove 12.12.12.26 peer-group)
```
router bgp 1321
 bgp log-neighbor-changes
 neighbor INIGROUP peer-group
 neighbor INIGROUP remote-as 4761
 !
 address-family ipv4
 exit-address-family

```
### Error Traceback
(Paste the complete traceback of the exception between quotes below)

```
fatal: [12.12.12.22]: FAILED! => {"changed": false, "msg": "cannot install config: Candidate config could not be applied\n% BGP: Peer 12.12.12.26 is being deactivated. Try it later\nFailed to apply command  no neighbor 12.12.12.26 peer-group INIGROUP\nAborting Rollback.\n\nRollback failed.Reverting back to the original configuration: flash:archive-Jan-26-10-35-55.894-1 ...\n\nTotal number of passes: 1\nRollback Done\n\nThe original configuration has been successfully restored.\n"}

```
