### ISSUE TITLE
Increase read_timeout on nxos_ssh get_interfaces send_command() call

### ISSUE THREAD

**Issue by ktbyers** [napalm-automation/napalm#2159]
Sometimes this does not complete in the allocated 10 seconds (will be even worse with a large number of interfaces).

Should probably increase to 30 or 60 seconds.

**Comment by ktbyers** [comment]
For some reason, could not reproduce in straight Python, only in napalm-ansible?

**Comment by ktbyers** [comment]
This playbook sometimes fails:

```yaml
---
- name: napalm nxos_ssh
  hosts: nxos1
  gather_facts: False
  tasks:
    - name: Retrieve get_facts, get_interfaces
      napalm.napalm.get_facts:
        filter: facts,interfaces
        dev_os: nxos_ssh

    - ansible.builtin.debug:
        var: napalm_facts
```
