### ISSUE TITLE
when using nxos_ssh when changing hostname receive error

### ISSUE THREAD

**Issue by omershtivi** [napalm-automation/napalm#637]
When used nxos_ssh changing device hostname I received the following issue:
`fatal: [LAB_POD2_1]: FAILED! => {"changed": false, "failed": true, "msg": "cannot install config: Search pattern never detected in send_command_expect: LAB\\_POD2\\_1\\-TEST\\#"}`

Rerun the playbook Password OK

The playbook:
```
omers@Ubuntu-Ansible-CTL:~/Naplam-Tests$ more Playbooks/Basic-Config-Checkpoint-Dryrun.yml
---
- name: Configuration replace
  hosts: N9K
  connection: local
  gather-facts: False
  tasks:
      - name: Generate-Configuration N9K
        template: src=../Templates/N9K-Checkpoint.j2 dest=../Configuration/{{ inventory_hostname }}

      - name: N9K Configuration Replace Check
        napalm_install_config:
             hostname: "{{ ip_address }}"
             username: "{{ username }}"
             password: "{{ password }}"
             dev_os: "{{ dev_os }}"
             config_file: ../Configuration/{{ inventory_hostname }}
             commit_changes: False
             replace_config: True
             diff_file: ../Diff/initial.diff
```
