### ISSUE TITLE
Extend a driver and reference it with napalm-ansible

### ISSUE THREAD

**Issue by radtrentasei** [napalm-automation/napalm#638]
As discussed in [115](https://github.com/napalm-automation/napalm-ansible/issues/115) I am bringing this topic to a broader audience. 

I am trying to write some custom methods for my project; e.g. get_service_policies(). 

I have created in my working directory the **custom_napalm/** folder with **ios.py** and **__init__.py** ; ios.py extends the IOSDriver adding the desired method as explained in [doc]( http://napalm.readthedocs.io/en/latest/tutorials/extend_driver.html)

Everything works fine when using this method from the main python script (run in the working directory).

What I am struggling to achieve is to refer this method in some ansible playbook using the napalm-ansible module. 

I understand the task has to be written as follows:

```
- name: get facts from device
  connection : local
  napalm_get_facts:
    hostname: "localhost"
    optional_args: {'port' : "{{local_port}}" }
    username: "{{ ansible_user }}"
    dev_os: "{{ os }}"
    password: "{{ ansible_password }}"
    filter: ["service_policies"]
  register: result
```

The problem is that the ansible module napalm_get_facts.py is executed in some tmp folder without the custom_napalm folder and that's why is not possible to find ios.py.

If I add directly the method to the napalm/ios.py file it works from the ansible module as well.
