### ISSUE TITLE
VLAN getters

### ISSUE THREAD

**Issue by 8radm1n** [napalm-automation/napalm#919]
Following on from a discussion in NTC slack. Adding VLAN getters would be a nice addition IMO.
@ktbyers mentioned that he is open to at least a discussion on adding VLAN getters.

Some closed issues in this topic from the past 
https://github.com/napalm-automation/napalm/issues/571
https://github.com/napalm-automation/napalm-base/issues/252

I need this functionality for mainly Junos and Cumulus drivers so can focus my energy there if there is some agreement to move forward.

CC @jobec

**Comment by jobec** [comment]
Proposed output format: A dictionary with keys per interface (as returned by `get_interfaces()`) containing a dictionary with `mode`, `tagged` and `untagged` keys.

* **mode:** the mode the port is in, one of `access`, `trunk`
* **tagged:** sorted list of integers with vlan IDs that are tagged
* **untagged:** one single vlan ID that is untagged.

```python
{
   "gi-0/0/1": {
       "mode": "access",
       "tagged": [],
       "untagged": 15,
   },
   "gi-0/0/2": {
       "mode": "trunk",
       "tagged": [],
       "untagged": 1,
   },
}
```

Some assumptions I made.

**Why these fields?**
They are most matching the 802.1Q standard and are applicable across most vendors and platforms.

**Why ``mode``, because it can be deducted from having `tagged` vlans?**
There are situations where a port shows as an access port, but has a `tagged` vlan id that's the voice vlan.

**Why no voice vlan?**
The voice vlan is another tagged vlan id.

**Why no Port vlan ID (PVID)**
When a port is in trunk, the single `untagged` vlan id represents the PVID.

**Why no operational and administrative mode**
This leaks in vendor specific implementations. As far as I know, I only saw negotiable trunk on IOS.

**Comment by tardoe** [comment]
What about a QinQ / dot1Q tunnelling use case?

**Comment by bobthebutcher** [comment]
Copying this from another closed issue which is a proposed model based on the open config model.
https://github.com/napalm-automation/napalm-base/issues/252#issuecomment-305963170

```
vlans:
  vlan:
    1:
      config:
          name: default
          status: active|suspended
    3:
      config:
          name: pre
          status: active|suspended
   4:
      config:
          name: pro
          status: ACTIVE|SUSPENDED
 interfaces:
   interface:
      et1:
        ethernet:
             switched-vlan:
                 config:
                       interface-mode: ACCESS|TRUNK
                       native-vlan: 1
                       access-vlan: 3
                       trunk-vlans: [3,4]
```
