### ISSUE TITLE
NAPALM validate - nxos - get_interfaces_ip not working

### ISSUE THREAD

**Issue by writememe** [napalm-automation/napalm#964]
### Description of Issue/Question

When attempting to use the napalm validate module in either Python or Ansible using the napalm-ansible for NXOS to validate the `get_interfaces_ip`, it appears that there maybe an issue locating `get_interfaces_ip` module for NXOS. Initially, I found the issue in Ansible, however it appears to be irrespective of using napalm-ansible or napalm.

### Did you follow the steps from https://github.com/napalm-automation/napalm#faq

- [x] Yes
- [ ] No

### napalm version
(Paste verbatim output from `pip freeze | grep napalm` between quotes below)

```
napalm==2.4.0
napalm-ansible==0.10.0
```

### Network operating system version
(Paste verbatim output from `show version` - or equivalent - between quotes below)

```
Cisco Nexus Operating System (NX-OS) Software
TAC support: http://www.cisco.com/tac
Documents: http://www.cisco.com/en/US/products/ps9372/tsd_products_support_series_home.html
Copyright (c) 2002-2017, Cisco Systems, Inc. All rights reserved.
The copyrights to certain works contained herein are owned by
other third parties and are used and distributed under license.
Some parts of this software are covered under the GNU Public
License. A copy of the license is available at
http://www.gnu.org/licenses/gpl.html.

NX-OSv9K is a demo version of the Nexus Operating System

Software
  BIOS: version 
  NXOS: version 7.0(3)I5(2)
  BIOS compile time:  
  NXOS image file is: 
  NXOS compile time:  2/16/2017 8:00:00 


Hardware
  cisco NX-OSv Chassis 
   with 8165360 kB of memory.
  Processor Board ID 9238C9BU8O8

  Device name: lab-nxos-01
  bootflash:    3509454 kB
Kernel uptime is 5 day(s), 0 hour(s), 32 minute(s), 41 second(s)

Last reset 
  Reason: Unknown
  System version: 
  Service: 

plugin
  Core Plugin, Ethernet Plugin

Active Package(s):
```

### Steps to Reproduce the Issue

Here is how to reproduce the issue in both systems:

#### Ansible

Below is a simple playbook to reproduce the error

```
---
- name: Validate interfaces
  hosts: all
  connection: local
  tasks:
  - name: Use Napalm to automatically validate existing interfaces
    napalm_validate:
      hostname: "{{ inventory_hostname }}"
      username: "{{ username }}"
      dev_os: "{{ os }}"
      password: "{{ password }}"
      validation_file: "validate.yml"
```
Below is the `validate.yml` file:

```
---
- get_facts:
    fqdn: lab-nxos-01.lab.dfjt.local
- get_bgp_neighbors:
    global:
      peers:
        192.168.30.13:
          description: lab-arista-01.lab.dfjt.local
          is_enabled: true
          is_up: true
          local_as: 65014
          remote_as: 65011
        192.168.30.1:
          description: lab-iosv-02.lab.dfjt.local
          is_enabled: true
          is_up: true
          local_as: 65014
          remote_as: 65013
      router_id: 192.168.40.14
- get_interfaces:
    Ethernet1/3:
      description: To lab-arista-01.lab.dfjt.local - Ethernet3
      is_enabled: true
      is_up: true
    Ethernet1/2:
      description: To lab-iosv-02.lab.dfjt.local - Ethernet0/2
      is_enabled: true
      is_up: true
    loopback0:
      description: Loopback Interface
      is_enabled: true
      is_up: true
- get_interfaces_ip:
    Ethernet1/3:
      ipv4:
        192.168.30.14:
          prefix_length: 30
    Ethernet1/2:
      ipv4:
        192.168.30.2:
          prefix_length: 30
    loopback0:
      ipv4:
        192.168.40.14:
          prefix_length: 32`
```
Whenever I comment out the `get_interfaces_ip` validation the other validation rules pass.
Whenever I use the same playbook and validation rules on other operating systems, it works.

### 

### Error Traceback
(Paste the complete traceback of the exception between quotes below)
#### Ansible

The following error is for Ansible:

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'NoneType' object has no attribute 'get'
fatal: [lab-nxos-01.lab.dfjt.local]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/home/vagrant/.ansible/tmp/ansible-local-12195tgkmXy/ansible-tmp-1555578768.4-250529955832985/AnsiballZ_napalm_validate.py\", line 113, in <module>\n    _ansiballz_main()\n  File \"/home/vagrant/.ansible/tmp/ansible-local-12195tgkmXy/ansible-tmp-1555578768.4-250529955832985/AnsiballZ_napalm_validate.py\", line 105, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/vagrant/.ansible/tmp/ansible-local-12195tgkmXy/ansible-tmp-1555578768.4-250529955832985/AnsiballZ_napalm_validate.py\", line 48, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_napalm_validate_payload_7tek3N/__main__.py\", line 260, in <module>\n  File \"/tmp/ansible_napalm_validate_payload_7tek3N/__main__.py\", line 239, in main\n  File \"/tmp/ansible_napalm_validate_payload_7tek3N/__main__.py\", line 139, in get_compliance_report\n  File \"/home/vagrant/.local/lib/python2.7/site-packages/napalm/base/base.py\", line 1660, in compliance_report\n    self, validation_file=validation_file, validation_source=validation_source\n  File \"/home/vagrant/.local/lib/python2.7/site-packages/napalm/base/validate.py\", line 204, in compliance_report\n    actual_results = getattr(cls, getter)(**kwargs)\n  File \"/home/vagrant/.local/lib/python2.7/site-packages/napalm/nxos/nxos.py\", line 1091, in get_interfaces_ip\n    ipv6_command, \"TABLE_intf\", \"ROW_intf\"\n  File \"/home/vagrant/.local/lib/python2.7/site-packages/napalm/nxos/nxos.py\", line 721, in _get_command_table\n    return self._get_reply_table(json_output, table_name, row_name)\n  File \"/home/vagrant/.local/lib/python2.7/site-packages/napalm/nxos/nxos.py\", line 717, in _get_reply_table\n    return self._get_table_rows(result, table_name, row_name)\n  File \"/home/vagrant/.local/lib/python2.7/site-packages/napalm/nxos/nxos.py\", line 706, in _get_table_rows\n    _table = parent_table.get(table_name)\nAttributeError: 'NoneType' object has no attribute 'get'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```

NOTE: Initially I was also getting an InsecureRequestWarning which I've disabled by using the command `export PYTHONWARNINGS="ignore:Unverified HTTPS request"`

#### Python

The following error is for Python:

```
Traceback (most recent call last):
  File "compliance.py", line 12, in <module>
    pprint.pprint(nxos.compliance_report("validate.yml"))
  File "/home/vagrant/.local/lib/python2.7/site-packages/napalm/base/base.py", line 1660, in compliance_report
    self, validation_file=validation_file, validation_source=validation_source
  File "/home/vagrant/.local/lib/python2.7/site-packages/napalm/base/validate.py", line 204, in compliance_report
    actual_results = getattr(cls, getter)(**kwargs)
  File "/home/vagrant/.local/lib/python2.7/site-packages/napalm/nxos/nxos.py", line 1091, in get_interfaces_ip
    ipv6_command, "TABLE_intf", "ROW_intf"
  File "/home/vagrant/.local/lib/python2.7/site-packages/napalm/nxos/nxos.py", line 721, in _get_command_table
    return self._get_reply_table(json_output, table_name, row_name)
  File "/home/vagrant/.local/lib/python2.7/site-packages/napalm/nxos/nxos.py", line 717, in _get_reply_table
    return self._get_table_rows(result, table_name, row_name)
  File "/home/vagrant/.local/lib/python2.7/site-packages/napalm/nxos/nxos.py", line 706, in _get_table_rows
    _table = parent_table.get(table_name)
AttributeError: 'NoneType' object has no attribute 'get'
```
This is my first ever GitHub issue that I've raised so hopefully there is enough detail and I'm not wasting your time.
